spring:
  application.name: demo-chat-ai

telegram:
  bot:
    login: 'login'
    token: 'token'
    optionsEnable: false
    options:
      proxyHost: proxy_host
      proxyPort: proxy_port
      proxyType: proxy_type

langchain4j.open-ai.chat-model:
  api-key: 'key'
  model-name: gpt-3.5-turbo
  log-requests: false
  log-responses: true
  max-retries: 1

logging.level.dev:
  langchain4j: INFO
  ai4j.openai4j: INFO


